name: Execute BPMN

on: workflow_dispatch

jobs:
  execute-bpmn:
    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4
  
      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Execute BPMN
        run: |
          wget https://downloads.camunda.cloud/release/camunda-bpm/run/7.21/camunda-bpm-run-7.21.0.zip
          unzip camunda-bpm-run-7.21.0.zip -d camunda-bpm-run
          cd camunda-bpm-run

          cp ../process.bpmn ./configuration/resources/

          ./start.sh 
          sleep 30
      - name: Run BPMN Process
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"variables":{}}' \
            http://localhost:8080/engine-rest/process-definition/key/process_a/start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
