name: Execute BPMN

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
jobs:
  execute-bpmn:
    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4
  
      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Execute BPMN
        env:
          GITHUB_TOKEN: ${{ secrets.TTT }}
        run: |
          wget https://downloads.camunda.cloud/release/camunda-bpm/run/7.21/camunda-bpm-run-7.21.0.zip
          unzip camunda-bpm-run-7.21.0.zip -d camunda-bpm-run
          cd camunda-bpm-run

          cp ../process.bpmn ./configuration/resources/

          ./start.sh 
          sleep 30
          
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"variables":{}}' \
            http://localhost:8080/engine-rest/process-definition/key/process_a/start)

          echo "Response from curl request process: $response"

          instance_id=$(echo $response | jq -r '.id')

          echo "Process instance ID: $instance_id"
          
          if [ "$instance_id" = "null" ]; then
            echo "Failed to start process instance"
            echo "Response from curl request: $response"
            exit 1
          fi

          sleep 10

          instance_status=$(curl -s http://localhost:8080/engine-rest/process-instance/$instance_id)
          echo "Process instance status: $instance_status"

          if [[ "$instance_status" == *"ended"* ]]; then
            echo "Process instance completed successfully"
          else
            echo "Process instance did not complete successfully. Fetching logs..."
            logs=$(curl -s http://localhost:8080/engine-rest/history/activity-instance?processInstanceId=$instance_id)
            echo "Process instance logs: $logs"
            exit 1
          fi
